version: '3.8'

services:
  flask-app-1:
    build: .
    container_name: flask-app-1
    ports:
      - "5001:5000"
    volumes:
      - ./visits.json:/app/visits.json
    restart: always

  flask-app-2:
    build: .
    container_name: flask-app-2
    ports:
      - "5002:5000"
    volumes:
      - ./visits.json:/app/visits.json
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

